title: SHOU AIO Lab
description: AI Oceanography Lab at Shanghai Ocean University 
markdown: kramdown
# If you publish in a repo that's NOT username.github.io, set baseurl to /your-repo-name
# baseurl: ""

# Optional: if you use a custom domain, add a CNAME file at the repo root and configure DNS
# url: "https://lab.example.com"
